default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Grahhs1995family
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_webpack_development

test:
  <<: *default
  database: rails_webpack_test


production:
  <<: *default
  database: rails_webpack_production
  
